### ISSUE TITLE
Closure confusion with IndNat

### ISSUE THREAD

**Issue by Boarders** [david-christiansen/pie-hs#11]
This isn't really an issue more a confusion of mine that I was hoping you could possibly clear up. In the implementation given [here]( https://github.com/jozefg/nbe-for-mltt/blob/master/nbe-explanation.md)
the induction principle for nats has the following representation as a neutral term:
```ocaml
...
and ne =
...
  | NRec of clos * nf * clos2 * ne
```

On the other hand the implementation here doesn't use closures for this neutral term. Is there a conceptual explanation for what is going on? On some level it seems like closures are only needed for introduction forms as these can be values whereas elimination forms need not capture their environment as they are stuck due to the presence of free variables. Is this way off or is there something else going on here?

**Comment by david-christiansen** [comment]
Hi! Sorry for the slow response, I missed this for some reason.

The difference here is one of how the theory is formulated. The theory that Gratzer implements in that tutorial would phrase the rule for `ind-Nat` as something like:

```
Γ ⊢ tgt : Nat     Γ, x : Nat ⊢ mot type
Γ ⊢ base : mot[zero/x]    Γ, y : Nat, z : mot[y/x] ⊢ step : mot[(add1 y)/x]
---------------------------------------------------------------------------
Γ ⊢ (ind-Nat tgt ((x) mot) base ((y z) step) : mot[tgt/x] 
```

In other words, the definition of `ind-Nat` doesn't involve functions at all, and it instead binds variables itself. Advantages of this approach include keeping the theory modular, so the different types are independent of each other, as well as allowing the "is a type" judgment to be used for the motive rather than the "function that returns an element of the universe" type, which can prevent some issues if you want to use `ind-Nat` to compute types and you only have one universe like Pie does. When this version of the rule binds variables, it needs to create closures for the same reason that `lambda` needs to.

Hope that's helpful.

**Comment by Boarders** [comment]
Thanks for clarifying @david-christiansen, lucid as always!
